import { Container } from "react-bootstrap"
// import './Internship.css'


export function Internship() {
  return (
    <>
      <Container className="mt-5">
        <div className="internship">
          <div id="comp-kpfaw7sg" className="_2Hij5" data-testid="richTextElement">
            <div className="element0">
              <h2 className="font_5">INTERNSHIP ANNOUNCEMENT</h2>
            </div>
          </div>
          <div id="comp-kpflgr5m" className="para" data-testid="richTextElement">
            <p className="font_2">
              We are offering Internships in different departments. This internship
              will help you to understand and enhance your skills while working with
              us. This internship is partially online and partially offline by
              keeping in mind your safety during the pandemic of COVID-19. This
              internship will help you to gain work experience or satisfy
              requirements for a qualification. This internship programme is framed
              by keeping in mind the All India Council of Technical Education
              (AICTE) norms &amp; guidelines.
            </p>
          </div>
          <div id="comp-kvjr99kw" className="_2Hij5" data-testid="richTextElement">
            <div className="element1">
              <h3 className="font_2">Open Positions</h3>
            </div>
          </div>
          <div id="comp-kpfbvy2g" className="_2Hij5" data-testid="richTextElement">
            <p className="font_2">
              Internship is open for the following positions (position code):
              <br />
              <br />
              1. Business Development Analyst Intern&nbsp; (IN01-2021)
              <br />
              2. Business Development Intern in Marketing (IN02-2021)
              <br />
              3. Business Development Intern in Sales (IN03-2021)
              <br />
              4. Business Development Intern in Research &amp; Operations
              (IN04-2021)
              <br />
              5. Business Development Intern in Management (IN05-2021)
              <br />
              6. Creative Website Designer (IN06-2021)
            </p>
          </div>
          <div className="verticalLine"></div>
          <div id="comp-kvjrfq2h" className="_2Hij5" data-testid="richTextElement">
            <div className="element1">
              <h3 className="font_2">Eligibility</h3>
            </div>
          </div>
          <div id="comp-kvp2a733" className="_2Hij5" data-testid="richTextElement">
            <p className="font_2">Open for all branches, 3rd and 4th year students</p>
          </div>
          <div className="verticalLine"></div>
          <div id="comp-kvjrjlxg" className="_2Hij5" data-testid="richTextElement">
            <div className="element1">
              <h3 className="font_2">Stipend&nbsp;</h3>
            </div>
          </div>
          <div id="comp-kvwdxpzh" className="_2Hij5" data-testid="richTextElement">
            <p className="font_2">
              Upto&nbsp;<span className="color_15">7-12%</span>&nbsp;of the revenue
              generated by the interns
              <br />
              <i>or</i>
              <br />
              Upto&nbsp;<span className="color_15">80,000 INR</span>
            </p>
          </div>
          <div className="verticalLine"></div>
          <div id="comp-kvjrkd1u" className="_2Hij5" data-testid="richTextElement">
            <div className="element1">
              <h3 className="font_2">Perks</h3>
            </div>
          </div>
          <div id="comp-kvwdykul" className="_2Hij5" data-testid="richTextElement">
            <p className="font_2">
              ~ Certificate of completion
              <br />
              ~ Letter of Appreciation
              <br />
              ~ Exposure with the organization
              <br />~ Direct interaction with the clients
            </p>
          </div>
          <div className="verticalLine"></div>
          <div id="comp-kvwe08dk" className="_2Hij5" data-testid="richTextElement">
            <div className="element1">
              <h3 className="font_2">Mode</h3>
            </div>
          </div>
          <div id="comp-kvwe0egz" className="_2Hij5" data-testid="richTextElement">
            <p className="font_2">
              <span className="color_14">Online</span>&nbsp;or&nbsp;
              <span className="color_14">Offline</span>; depends on student's will
            </p>
          </div>
          <div className="verticalLine"></div>
          <div id="comp-kvjrne98" className="_2Hij5" data-testid="richTextElement">
            <div className="element1">
              <h3 className="font_2">Application Process</h3>
            </div>
          </div>
          <div id="comp-kvwe2275" className="_2Hij5" data-testid="richTextElement">
            <p className="font_2">
              Interested applicants are encouraged to submit an expression of
              interest through an e-mail.
              <br />
              Please ensure the below documents should be attached to the e-mail:
              <br />
              <br />- A concise cover letter that describes your suitability for
              this position (max 1 page)
              <br />- A copy of your current CV.
            </p>
          </div>
          <div id="comp-kvwe1a8l" className="_2Hij5" data-testid="richTextElement">
            <div className="verticalLine1"></div>
            <br />
            <p className="font_2">
              As a follow-up to the application, our team will be visiting to the
              campus and invite the applicants for interview. The interview will
              include two elements:
              <br />
              <br />
              <div className="element2">Element 1</div>
              <br />
              We will ask you to prepare a 7-8 minute presentation in which you
              address 3 things:
              <br />
              1. Your CV
              <br />
              2. Your Passion for applied position
              <br />
              3. General skills, your attitude to teamwork, feeling regarding
              interdisciplinary activities
              <br />
              <br />
              <div className="element2">Element 2</div>
              <br />
              This will be followed by a conversation with members of our
              organization. The applicant will be expected to explain what his
              contribution might be to the advertised position. The entire interview
              is scheduled to take around 12 minutes.
              <br />
              <br />
              <div className="verticalLine1"></div>
              <br />
              Applications can be applied through e-mail or the link given below
              <br />
              <br />
              <div className="btn">
                <a href="https://dare2compete.com/o/lsKFtfX?lb=0YxdjR5">
                  Start Today!
                </a>
              </div>
              <br />
              <div className="verticalLine1"></div>
              <br />
              Duration Of The Internship: <b>4 Weeks</b>
            </p>
            <br />
            <div className="verticalLine1"></div>
          </div>
        </div>
      </Container>
     
    </>


  )
}